#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

// Use preprocessor directives to enforce byte alignment packing, ensuring the file header is strictly 44 bytes when written
typedef struct __attribute__((packed)) {
    char riff_header[4];      // 0-3: "RIFF"
    uint32_t wav_size;        // 4-7: 50000 + 44
    char wave_header[4];      // 8-11: "WAVE"

    char fmt_header[4];       // 12-15: "fmt "
    uint32_t fmt_chunk_size;  // 16-19: 16
    uint16_t audio_format;    // 20-21: 1 (PCM)
    uint16_t num_channels;    // 22-23: 1 (Monophonic)
    uint32_t sample_rate;     // 24-27: 6400
    uint32_t byte_rate;       // 28-31: 12800
    uint16_t sample_alignment;// 32-33: 2
    uint16_t bit_depth;       // 34-35: 16

    char data_header[4];      // 36-39: "data"
    uint32_t data_bytes;      // 40-43: 50000
} WavHeader;

int main() {
    FILE *raw_file;
    FILE *wav_file;
    
    // Open the binary file generated by the Python script for reading
    raw_file = fopen("recording.bin", "rb");
    if (raw_file == NULL) {
        printf("Error: Could not open recording.bin\n");
        return 1;
    }

    fseek(raw_file, 0, SEEK_END);
    uint32_t file_size = ftell(raw_file);
    fseek(raw_file, 0, SEEK_SET); 

    // Create the .wav file we want to write to
    wav_file = fopen("output_audio.wav", "wb");
    if (wav_file == NULL) {
        printf("Error: Could not create output_audio.wav\n");
        fclose(raw_file);
        return 1;
    }

    // 1. Initialize and write the 44-byte WAV Header
    WavHeader header;
    memcpy(header.riff_header, "RIFF", 4);
    header.wav_size = file_size + 36; 
    memcpy(header.wave_header, "WAVE", 4);
    
    memcpy(header.fmt_header, "fmt ", 4);
    header.fmt_chunk_size = 16;
    header.audio_format = 1;
    header.num_channels = 1;
    header.sample_rate = 22050; 
    header.byte_rate = 22050; // 22050 * 8 * 1 / 8
    header.sample_alignment = 1; // 8 * 1 / 8
    header.bit_depth = 8;
    
    memcpy(header.data_header, "data", 4);
    header.data_bytes = 50000; 

    // Write Header to the wav file
    fwrite(&header, sizeof(WavHeader), 1, wav_file);

    // 2. Loop to read the raw ADC data and perform scaling/conversion
    uint8_t raw_adc_value;
    
    while (fread(&raw_adc_value, sizeof(uint8_t), 1, raw_file) == 1) {
        
        fwrite(&raw_adc_value, sizeof(int8_t), 1, wav_file);
    }

    // 3. Close the files and complete cleanup
    fclose(raw_file);
    fclose(wav_file);

    printf("Conversion successful! Saved as output_audio.wav\n");

    return 0;
}